In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('Energy_and_Water_Data_Disclosure_for_Local_Law_84_2020__Data_for_Calendar_Year_2019_.csv')

C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3063: DtypeWarning: Columns (14) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [4]:
df.head()

,Order,Property Id,Property Name,Parent Property Id,Parent Property Name,City Building,BBL - 10 digits,"NYC Borough, Block and Lot (BBL) self-reported",NYC Building Identification Number (BIN),Address 1 (self-reported),...,Water Use (All Water Sources) (kgal),Water Use Intensity (All Water Sources) (gal/ft²),Water Required,Generation Date,Latitude,Longitude,Community Board,Council District,Census Tract,NTA
0,1,7365,1155,Not Applicable: Standalone Property,Not Applicable: Standalone Property,No,1009970029,1009970029,1022631,1155 Avenue of the Americas,...,Not Available,Not Available,No,05/28/2020,40.756631,-73.982826,105.0,4.0,119.0,Midtown-Midtown South
1,2,8139,200,Not Applicable: Standalone Property,Not Applicable: Standalone Property,No,1013150001,1013150001,1037545,200 East 42nd St.,...,7310.6,19.02,Yes,05/28/2020,40.750698,-73.974306,106.0,4.0,88.0,Turtle Bay-East Midtown
2,3,8604,114,Not Applicable: Standalone Property,Not Applicable: Standalone Property,No,1009990019,1009990019,1022667,114 West 47th st,...,Not Available,Not Available,No,05/28/2020,40.758310,-73.982504,105.0,4.0,125.0,Midtown-Midtown South
3,4,8841,733,Not Applicable: Standalone Property,Not Applicable: Standalone Property,No,1013190047,1013190047,1037596,733 Third Avenue,...,Not Available,Not Available,No,05/28/2020,40.753074,-73.972753,106.0,4.0,90.0,Turtle Bay-East Midtown
4,5,11809,Conde Nast Building,Not Applicable: Standalone Property,Not Applicable: Standalone Property,No,1009950005,1009950005,1085682,4 Times Square,...,Not Available,Not Available,No,05/28/2020,40.756181,-73.986244,105.0,4.0,119.0,Midtown-Midtown South

In [6]:
df.shape

(28807, 67)

In [9]:
df.columns

Index(['Order', 'Property Id', 'Property Name', 'Parent Property Id',
       'Parent Property Name', 'City Building', 'BBL - 10 digits',
       'NYC Borough, Block and Lot (BBL) self-reported',
       'NYC Building Identification Number (BIN)', 'Address 1 (self-reported)',
       'Address 2 (self reported)', 'Postal Code', 'Street Number',
       'Street Name', 'Borough', 'DOF Gross Floor Area (ft²)',
       'Self-Reported Gross Floor Area (ft²)',
       'Primary Property Type - Self Selected',
       'List of All Property Use Types at Property',
       'Largest Property Use Type',
       'Largest Property Use Type - Gross Floor Area (ft²)',
       '2nd Largest Property Use Type',
       '2nd Largest Property Use - Gross Floor Area (ft²)',
       '3rd Largest Property Use Type',
       '3rd Largest Property Use Type - Gross Floor Area (ft²)', 'Year Built',
       'Number of Buildings', 'Occupancy', 'Metered Areas (Energy)',
       'Metered Areas (Water)', 'ENERGY STAR Score', 'Source EUI (kBtu/ft²)',
       'Weather Normalized Site EUI (kBtu/ft²)', 'Site EUI (kBtu/ft²)',
       'Weather Normalized Source EUI (kBtu/ft²)',
       'Weather Normalized Site Electricity Intensity (kWh/ft²)',
       'Weather Normalized Site Natural Gas Intensity (therms/ft²)',
       'Fuel Oil #1 Use (kBtu)', 'Fuel Oil #2 Use (kBtu)',
       'Fuel Oil #4 Use (kBtu)', 'Fuel Oil #5 & 6 Use (kBtu)',
       'Diesel #2 Use (kBtu)', 'Kerosene Use (kBtu)', 'Propane Use (kBtu)',
       'District Steam Use (kBtu)', 'District Hot Water Use (kBtu)',
       'District Chilled Water Use (kBtu)', 'Natural Gas Use (kBtu)',
       'Weather Normalized Site Natural Gas Use (therms)',
       'Electricity Use - Grid Purchase (kBtu)',
       'Electricity Use - Grid Purchase (kWh)',
       'Weather Normalized Site Electricity (kWh)',
       'Annual Maximum Demand (kW)', 'Annual Maximum Demand (MM/YYYY)',
       'Total GHG Emissions (Metric Tons CO2e)',
       'Direct GHG Emissions (Metric Tons CO2e)',
       'Indirect GHG Emissions (Metric Tons CO2e)',
       'Water Use (All Water Sources) (kgal)',
       'Water Use Intensity (All Water Sources) (gal/ft²)', 'Water Required',
       'Generation Date', 'Latitude', 'Longitude', 'Community Board',
       'Council District', 'Census Tract', 'NTA'],
      dtype='object')

In [35]:
len(df)

28807

In [36]:
df = df.drop_duplicates()
len(df)

28807

In [16]:
len(df['Property Id'].unique())

27703

In [33]:
unique = df[['Property Id','Property Name']].groupby(by=['Property Id']).count().reset_index().rename(columns={'Property Name':'count'})
non_unique = unique.loc[unique['count'] > 1]
non_unique

       Property Id  count
54         1409171      2
74         1439975      2
973        1712194      2
1283       2008956      2
1284       2008963      2
...            ...    ...
26990     12069093      2
26999     12069142      2
27262     12347072      2
27470     12683770      2
27687     12914534      2

[1101 rows x 2 columns]

In [41]:
non_unique['count'].value_counts()

2    1098
3       3
Name: count, dtype: int64

In [34]:
df_non_unique = df[df['Property Id'].isin(non_unique['Property Id'])]
df_non_unique

,Order,Property Id,Property Name,Parent Property Id,Parent Property Name,City Building,BBL - 10 digits,"NYC Borough, Block and Lot (BBL) self-reported",NYC Building Identification Number (BIN),Address 1 (self-reported),...,Water Use (All Water Sources) (kgal),Water Use Intensity (All Water Sources) (gal/ft²),Water Required,Generation Date,Latitude,Longitude,Community Board,Council District,Census Tract,NTA
58,55,1409171,NE - COURT SQUARE I,Not Applicable: Standalone Property,Not Applicable: Standalone Property,No,4000790030,4000790030,4307108,1 Court Square,...,20972.5,14.6,Yes,03/27/2020,40.746704,-73.943476,402.0,26.0,19.0,Hunters Point-Sunnyside-West Maspeth
60,56,1409171,NE - COURT SQUARE I,Not Applicable: Standalone Property,Not Applicable: Standalone Property,No,4000790030,4-00079-0030,4307108,1 Court Square,...,20972.5,14.6,Yes,05/01/2020,40.746704,-73.943476,402.0,26.0,19.0,Hunters Point-Sunnyside-West Maspeth
81,76,1439975,19 East 57th Street,Not Applicable: Standalone Property,Not Applicable: Standalone Property,No,1012930014,1012930014,1086164,19E 57th Street,...,1857.6,18.39,No,03/20/2020,40.762621,-73.973128,105.0,4.0,11202.0,Midtown-Midtown South
82,77,1439975,19 East 57th Street,Not Applicable: Standalone Property,Not Applicable: Standalone Property,No,1012930014,1012930014,1086164,19E 57th Street,...,1857.6,18.39,No,05/01/2020,40.762621,-73.973128,105.0,4.0,11202.0,Midtown-Midtown South
979,976,1712194,Red Circle NYC Corp,Not Applicable: Standalone Property,Not Applicable: Standalone Property,NaN,1007680050,1-00768-0050,1013884,220 West 19 Street,...,2567.5,23.33,Yes,05/01/2020,40.742093,-73.998528,104.0,3.0,87.0,Hudson Yards-Chelsea-Flatiron-Union Square
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28364,28365,12347072,1523 63rd Street,Not Applicable: Standalone Property,Not Applicable: Standalone Property,NaN,3055300016,3055300016,2006769,1523 63rd Street,...,Not Available,Not Available,No,10/22/2020,40.624081,-73.995238,311.0,38.0,250.0,Bensonhurst West
28575,28573,12683770,(71082A) Bay Plaza Macy's,Not Applicable: Standalone Property,Not Applicable: Standalone Property,NaN,Not Available,Not Available,Not Available,250 BAYCHESTER AVENUE,...,501.5,3.91,NaN,10/27/2020,40.866225,-73.830576,210.0,12.0,46201.0,Co-op City
28576,28574,12683770,(71082A) Bay Plaza Macy's,Not Applicable: Standalone Property,Not Applicable: Standalone Property,NaN,2051410001,2051410001,2119954,250 BAYCHESTER AVENUE,...,Not Available,Not Available,No,10/28/2020,40.866225,-73.830576,210.0,12.0,46201.0,Co-op City
28790,28791,12914534,2128 Ocean Avenue,Not Applicable: Standalone Property,Not Applicable: Standalone Property,NaN,3067827506,3067827506,3425675,2128 Ocean Avenue,...,Not Available,Not Available,No,11/01/2020,40.609857,-73.953403,315.0,48.0,550.0,Madison
28791,28792,12914534,2128 Ocean Avenue,Not Applicable: Standalone Property,Not Applicable: Standalone Property,NaN,3067827506,3067827506,3425675,2128 Ocean Avenue,...,Not Available,Not Available,No,11/01/2020,40.609857,-73.953403,315.0,48.0,550.0,Madison

In [42]:
import geopandas as gpd

In [ ]:
# with geopandas

fig, ax = plt.subplots(1, figsize=(10,10))

df.plot(ax=ax, column='City Building', k=10, scheme='Quantiles', legend=True, 
              legend_kwds={'loc': 'upper left'})